### ISSUE TITLE
Clearing of cache for wallets

### ISSUE THREAD

**Issue by evesnow91** [zillet/zillet#40]
When you log out of your wallet, and tries to log in to a different wallet, you have to clear your cache before you can access this new wallet at the moment. 

This might confuse the Users of the wallet as their new keystore/private key resolve to the previous address.

**Suggestion:** Clear the cache and do a hard reload everytime a User logs out of the wallet.

**Comment by man15h** [comment]
Hey @evesnow91, I have not encountered this issue, I don't think if the cache is the culprit for the address, I'm only storing the sensitive info into the Vuex store, which set to empty after page refresh or reload.

**Comment by man15h** [comment]
I think I find out the real culprit. It's happening because of the default account returned by the ZilliqaJs is the 0th index. Let's say you already have a Zilliqa wallet (old wallet). one day you create a new wallet on Zillet, then access the wallet for some time and then you `logout`. Further, you log in with your old wallet but the address you'll see is the address belongs to the newly created wallet. why is that? the `logout`

**Comment by man15h** [comment]
@75afb5ee68eec20d7beec34bc0bc97227d8cdbc1
